config/routes.rb
Rails.application.routes.draw do

  root 'galerie#index'
  get 'upload' => 'galerie#new'
  post 'upload' => 'galerie#create'

  get 'image/:id' => 'galerie#show'
  get 'search' => 'galerie#recherche'
  get 'search/:tag' => 'galerie#recherche'
  get 'image/download/:id' => 'galerie#telecharger'

end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :titre, :tag, presence: true
  
  has_attached_file :avatar, :styles => { :medium => "300x200!", :thumb => "100x66!" }, :default_url => "/images/:style/missing.png"
  validates_attachment :avatar, :presence => true, :content_type => { :content_type => ["image/jpeg", "image/png", "image/gif", "image/svg"] }, :size => { :in => 0..5.megabytes }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galerie_controller.rb
class GalerieController < ApplicationController
  def index
    @images = Image.all.reverse
    @tags = [] << Image.all.map { |x| x.tag.split(' ')}
    @tags = @tags.flatten.uniq.sample(3)
    @exemple = @tags.join(', ')
  end

  def show
    @image = Image.find(params[:id])
    @titre = @image.titre
    @tag = @image.tag 
    @nom_fichier = @image.avatar_file_name
    @poids_image = @image.avatar_file_size/1000
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.create(params_image)
    if @image.save
      flash[:success] = "Votre image a bien été ajoutée dans la galerie."
      redirect_to root_path
    else
      flash[:error] = "Une erreur est survenue."
      render 'new'
    end
  end

  def recherche
    @recherche = params[:tag].split(' ')
    @image = []
    if params[:tag] == "" 
      redirect_to root_path
    else
      @recherche.each do |r|
        @image << Image.where("tag like ?", "%#{r}%")
      end
    @images = @image.flatten.uniq
    @tags = [] << Image.all.map { |x| x.tag.split(' ')}
    @tags = @tags.flatten.uniq.sample(3)
    @exemple = @tags.join(', ')
    render 'index'
    end
  end

  def telecharger
  @telecharger= Image.find(params[:id])

  send_file @telecharger.avatar.path,
              :filename => @telecharger.avatar_file_name,
              :type => @telecharger.avatar_content_type,
              :disposition => 'attachment'
end

  private

  def params_image
    params.require(:upload).permit(:titre, :tag, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galerie_helper.rb
module GalerieHelper
end

app/views/galerie/index.erb
<div class="galerie-topbar">
	<h1>Galerie photos</h1>

	<div class="galerie-recherche">
		<%= form_tag "/search", :method => 'get' do %>
			<%= text_field_tag :tag, params[:tag], placeholder:"Rechercher des images par tags, exemple \"#{@exemple}\", ... Vous pouvez rechercher plusieurs tags en les séparant par des espaces." %>

			<%= submit_tag 'Rechercher' %>
		<% end %>
	</div>
</div>

<% if !current_page?('/') %>
	<div class="retour-galerie">
		<a href="/"><i class="fa fa-arrow-left"></i>Retour à la galerie</a>
	</div>
<% end %>

<div class="galerie-photos">
	<% if @images == [] && current_page?('/')%> 
		<div class="aucune-photo">
			Aucune photo dans la galerie.
		</div>
	<% elsif @images == [] %> 
		<div class="aucune-photo">
			Aucune photo ne correspond à votre recherche.
		</div>
	<% else %>
		<% @images.each do |i| %>
			<div class="photos">
				<a href="image/<%= i.id %>">
					<%= image_tag i.avatar.url(:medium) %>
				</a>
				<div class="photos-infos">
					<div><%= i.titre %></div>
					<div>
						<% i.tag.split(' ').each do |tag| %>
							<a href="/search/<%= tag %>"><%= tag %></a>
						<% end %>
					</div>
				</div>	
			</div>	
		<% end %>
	<% end %>

	<% if !current_page?('/') %>
		<div class="retour-galerie">
			<a href="/"><i class="fa fa-arrow-left"></i>Retour à la galerie</a>
		</div>
	<% end %>
</div>


<div class ="galerie-bottombar">
	<%= link_to 'Ajouter une photo', upload_path %>
</div>

app/views/galerie/new.erb
<div class="galerie-ajout">
  <div class="galerie-formulaire">
    <h1>Ajouter votre photo</h1>
  
    <%= form_for :upload do |f| %>
	   	<div class="galerie-formulaire-champ">
	   		<%= f.label :titre %>
	   		<%= f.text_field :titre %>
			</div>

			<div class="galerie-formulaire-champ">
			  <%= f.label :tag %>
			  <%= f.text_field :tag %>
			</div>

			<div class="galerie-formulaire-champ">
	    	<%= f.file_field :avatar %>
			</div>

	    <div class="galerie-formulaire-bouton">
	      <%= link_to 'Retour', root_path %>
	      <%= f.submit 'Envoyer' %>
	    </div>
    <% end %>

  </div>
</div>

app/views/galerie/show.erb
<div class="galerie-visuel">
  <div class="galerie-image-show">
    <div class="galerie-titre-photo">
      <h1><%= @image.titre %></h1>
    </div>

    <div class="galerie-image-visu">
      <%= image_tag @image.avatar.url %>
    </div>

    <div class="galerie-telecharger">
      <a href="/image/download/<%= @image.id %>">Télécharger</a>
    </div>

    <div class="galerie-image-infos">
      <!-- Insérer ici le each pour sortir en auto les infos de l'image -->
      <div class="galerie-infos-ligne"><p>Titre:</p><p><%= @titre %></p></div>
      <div class="galerie-infos-ligne"><p>Tags:</p><p><%= @tag %></p></div>
      <div class="galerie-infos-ligne"><p>Nom de l'image:</p><p><%= @nom_fichier %></p></div>
      <div class="galerie-infos-ligne"><p>Poids de l'image:</p><p><%= @poids_image %> Ko</p></div>
    </div>
  </div>
  
  <div class="galerie-bottombar">
    <%= link_to 'Retour à la galerie', root_path %>
  </div>
</div>

app/views/layouts/_flash.erb
<% if flash[:success] %>
  <div class='label label-success'><%= flash[:success] %></div>
<% elsif flash[:error] %>
  <div class='label label-error'><%= flash[:error] %></div>
<% elsif flash[:notice] %>
  <div class='label label-notice'><%= flash[:notice] %></div>
<% else %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>GaleriePhotos</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/flash' %>
<%= yield %>

</body>
</html>